version: '3.3'

services:
    app:
        container_name: app
        build: ./
        ports:
            - 8090:8000
        volumes:
            - ./:/var/www/html

    db:
        image: mysql
        container_name: db
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_USER: spallian
            MYSQL_PASSWORD: spallian
            MYSQL_DATABASE: blog
